version: '3.9'
services:
  db:
    image: timescale/timescaledb:2.13.0-pg16
    environment:
      POSTGRES_USER: acera
      POSTGRES_PASSWORD: acera
      POSTGRES_DB: acera
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./packages/api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./packages/api:/app
    environment:
      DATABASE_URL: postgresql://acera:acera@db:5432/acera
    depends_on:
      - db
    ports:
      - '8000:8000'
  web:
    build: ./apps/web
    command: pnpm run dev
    volumes:
      - ./apps/web:/app
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - api
    ports:
      - '3000:3000'
volumes:
  db_data: 