[tool.poetry]
name = "acera-api"
version = "2.0.0"
description = "AI-powered trading platform with Bloomberg Terminal features"
authors = ["Acera Team <team@acera.ai>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
uvloop = "^0.21.0"
pydantic = "^2.11.0"
aiohttp = "^3.10.0"
asyncio = "^3.4.3"
openai = "^1.58.0"
python-dotenv = "^1.0.0"
httpx = "^0.28.0"
redis = "^5.0.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.0"
alembic = "^1.13.0"
python-multipart = "^0.0.9"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pytest = "^8.0.0"
pytest-asyncio = "^0.24.0"
pytest-cov = "^6.0.0"
requests = "^2.32.4"

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"
isort = "^5.13.0"
flake8 = "^7.0.0"
mypy = "^1.11.0"
pre-commit = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 